services:
  nginx:
    image: nginx:1.27.2
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/nginx.conf.d:/etc/nginx/nginx.conf.d:ro
      - ./logs:/var/log/nginx
      - ../frontend:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app
    ports:
      - "8081:8081"
    networks:
      - sportwear-net